build.gradle
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3PutJob.java

Getting error 'MetadataAccessImpl cannot be converted to MetadataAccess'.

Update SDK 3.2.9

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/DeepStorageBrowserPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/createbucket/CreateBucketPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/Ds3PanelPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3TreeTablePresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/interruptedjobwindow/JobInfoPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/localfiletreetable/LocalFileTreeTablePresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/metadata/MetadataPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/modifyjobpriority/ModifyJobPriorityPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/settings/SettingPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/savedSessionStore/SavedSessionStore.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/CheckNetwork.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/DeepStorageBrowserTaskProgressView.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/FileSizeFormat.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/Priority.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/PriorityFilter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/ValueTreeTableCell.java
dsb-gui/src/test/java/com/spectralogic/dsbrowser/gui/util/PriorityFilterTest.java
gradle/wrapper/gradle-wrapper.properties

Ok, so the multi-select change we made to the local file browser should be applied to the DS3 file browser as well for consistency.
As long as I was fixing that, I took a stab at some low-hanging fixes.

Ds3 panel multiclick MacOS

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3TreeTablePresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/license/LicensePresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/localfiletreetable/LocalFileTreeTablePresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/newsession/NewSessionModel.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/newsession/NewSessionPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/newSessionService/SessionModelService.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/savedSessionStore/SavedSession.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/savedSessionStore/SavedSessionStore.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/sessionStore/Session.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/CreateConnectionTask.java
dsb-gui/src/main/resources/com/spectralogic/dsbrowser/gui/components/newsession/newsession.fxml
dsb-gui/src/main/resources/lang_en.properties
dsb-gui/src/test/java/com/spectralogic/dsbrowser/gui/services/newSessionService/SessionModelServiceTest.java

It took some cleanup and debugging but SSL works.

SSL added for feature

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/CreateConnectionTask.java
dsb-gui/src/main/resources/lang_en.properties

Got the build version from the localization file, added it to the client builder.

Added user agent to the client builder

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3TreeTablePresenter.java

After reading the documentation, this turned out to be a simple change.

BPB-142 Multi-clicking the load more no longer causes issues

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/ShutdownServiceImpl.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/deletefiles/DeleteItemPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/Ds3PanelPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3TreeTablePresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/localfiletreetable/LocalFileTreeTablePresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/physicalplacement/PhysicalPlacementPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/CreateConnectionTask.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/Ds3PutJob.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/GetBucketTask.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/PhysicalPlacementTask.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/RecoverInterruptedJob.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/ParseJobInterruptionMap.java

We now check to see if our destination is read-only or our source is write-only before we transfer to/from the BP.

Bpb 86 139

---

dsb-gui/src/main/resources/lang_en.properties

Also applies to the "About" pane

Change title from Deep Storage Browser to BlackPearlEonBrowser

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/metadata/MetadataPresenter.java
dsb-gui/src/test/java/com/spectralogic/dsbrowser/gui/components/metadata/MetadataPresenterTest.java

Reduction in code, browser now displays all metadata, and no longer converts epoch to date.

BPB-164 Metadata displays sanely now

---

dsb-gui/src/main/resources/com/spectralogic/dsbrowser/gui/components/settings/settings.fxml

The behavior this button provided was put into the 'showcachejob' button in the jobs pane.

BPB-168 - Remove checkbox that doesn't do anything

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/Ds3PanelPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/ds3Panel/Ds3PanelService.java

Small change, while I was fixing alerting a stray ' got introduced, better logging revealed the issue.

After I got an error this one turned out to be pretty simple

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/createfolder/CreateFolderPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3TreeTablePresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3TreeTableValue.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/ds3Panel/CreateService.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/RefreshCompleteViewWorker.java

Include the current path for the CreateFolderTask

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3TreeTablePresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/localfiletreetable/LocalFileTreeTablePresenter.java

Very similar to the task for the other direction.
Updated some names to be cleaner while I was there.

Bpb 211 - Null Pointer in drag event

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/Ds3PutJob.java

Another small change, I missed a place where we didn't replace the delimiter.

Found a place where we reason about dlim backwards

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/Ds3GetJob.java

Updated getJob so that we catch illegal characters before they hit the filesystem.

We now catch illegal characters in filesystem

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/Ds3PanelPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/ds3Panel/DeleteService.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/GetNoOfItemsTask.java

Fix a NoSuchElementException:
Exception in thread "JavaFX Application Thread" java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:135)
at com.spectralogic.dsbrowser.gui.services.ds3Panel.DeleteService.lambda$managePathIndicator$1(DeleteService.java:159)
at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
at java.security.AccessController.doPrivileged(Native Method)
at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)

Only refresh and show path if something is selected

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/localfiletreetable/LocalFileTreeTablePresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/Ds3GetJob.java

Given feedback from DVT:
Removed space between Black and Pearl
Added the name of the exception to an error

Better errors

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/Ds3GetJob.java

Small change, we're making sure we call listObjects only on folders.

We now only call listObjects on folders

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/Ds3PanelPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3TreeTableItem.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3TreeTablePresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/GetBucketTask.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/SearchJobTask.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/BucketUtil.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/GetStorageLocations.java
dsb-integration/src/test/java/com/spectralogic/dsbrowser/integration/BucketUtilTest.java
dsb-integration/src/test/java/com/spectralogic/dsbrowser/integration/tasks/GetBucketTaskTest.java

Bpb 260 storage locations

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3TreeTableItem.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/ds3Panel/Ds3PanelService.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/GetBucketTask.java

We now short circuit check for children on treeItem Type File
Remove unused import
Check for null

We should short-circut checkingt for children on file

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/DeepStorageBrowserPresenter.java

Very small PR, dealt with the verbosity of a log message in DeepStorageBrowserPresenter

Removed some very verbose logging

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/DeepStorageBrowserPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/about/AboutPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/JobWorkers.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/ds3Panel/CreateService.java
dsb-integration/src/test/java/com/spectralogic/dsbrowser/integration/CancelJobsWorkerTest.java
dsb-integration/src/test/java/com/spectralogic/dsbrowser/integration/CloseConfirmationHandlerTest.java
dsb-integration/src/test/java/com/spectralogic/dsbrowser/integration/tasks/Ds3GetJob_Test.java
dsb-integration/src/test/java/com/spectralogic/dsbrowser/integration/tasks/Ds3PutJobTest.java
dsb-integration/src/test/java/com/spectralogic/dsbrowser/integration/tasks/RecoverInterruptedJobTest.java

With this change we allow the user of the browser to add an arbitrary number of tasks at once, eventually they will saturate their network link or run out of JVM memory.

Allow an uncapped number of tasks at once

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/DeepStorageBrowserPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/interruptedjobwindow/JobInfoPresenter.java

Fairly small change, the placeholder was being set all the time, and we were counting interrupted jobs wrong.

It turns out we were adding the label even if we had contents?

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/DeepStorageBrowserPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/localfiletreetable/LocalFileTreeTablePresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/savedSessionStore/SavedSessionStore.java

Looking over Rob's log file there are actually two separate null pointers.

Bpb-315 - Local file tree 'explodes'

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3TreeTableItem.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/BucketUtil.java

To ensure the correct number of items get loaded.

Load the correct number of items

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/GetBucketTask.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/BucketUtil.java
dsb-integration/src/test/java/com/spectralogic/dsbrowser/integration/BucketUtilTest.java

This is an attempt to distinguish the load more code from the normal path and have the correct behavior in each case.

Bucket Util Fix

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/logservice/ApplicationLoggerSettings.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/settings/LogSettings.java

Small change should make log rolling better.

Fixed the maximum number of logs

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/DateTimeUtils.java

I saw this as I was reading some code, I think using constants makes this more readable.

I thought this was hard to read so I fixed it

---

dsb-gui/src/main/resources/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/ds3treetable.fxml

We can now resize ds3treeTable to be arbitraily tall

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/GetJob.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/JobTask.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/PutJob.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/data/GetJobData.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/data/JobData.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/data/PutJobData.kt
dsb-gui/src/main/resources/lang_en.properties

Pretty minor change, this adds the start time to the title of jobs.

Adding the time to job titles

---

build.gradle
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/GetJob.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/JobFacade.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/JobService.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/JobTask.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/PutJob.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/data/GetJobData.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/data/JobData.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/data/PutJobData.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/factories/GetJobFactory.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/factories/PutJobFactory.kt
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/jobService/factories/RecoverJobFactory.kt
dsb-gui/src/test/java/com/spectralogic/dsbrowser/gui/services/jobService/JobServiceTest.kt

This isn't perfect but it makes it possible to exit a transfer job early.
This also fixes an issue with paths more than the OS ulimit deep.

Bpb359: Intermediate do not merge

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/metadata/MetadataPresenter.java
dsb-gui/src/main/resources/com/spectralogic/dsbrowser/gui/components/metadata/metadata.css
dsb-gui/src/main/resources/com/spectralogic/dsbrowser/gui/components/metadata/metadata.fxml

By replacing the label with a semi-hidden text field we get the ability to select and copy.

Path is now selectable

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/Ds3PanelPresenter.java

Minor change, added ability to use tab as button.

New Session tab now acts as new session button

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/Ds3PanelPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/physicalplacement/PhysicalPlacementTapeEntryModel.java
dsb-gui/src/main/resources/com/spectralogic/dsbrowser/gui/components/physicalplacement/physicalplacement.fxml

This is a really small PR,
We have a typo in our FXML

Found the error, looks like the FXML was set up wrong

---

Builders/Linux/build.sh
Builders/Windows/SetupProject/Version.cs
build.gradle
dsb-gui/build.gradle
dsb-integration/build.gradle

Small PR, update versions of BP and assertJ

Version Bump

---

dsb-gui/src/main/resources/lang_en.properties

This label is more accurate as to the behavior we provide.

Fixed label

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/DeepStorageBrowserPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/ds3Panel/Ds3PanelService.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/Popup.java
dsb-gui/src/main/resources/com/spectralogic/dsbrowser/gui/components/settings/settings.fxml

This should un-resizeable windows resizable.

Settings and file properties resizeable

---

Builders/Linux/build.sh
Builders/Mac/build.sh
build.gradle
dsb-gui/build.gradle

Version bump 5.0.2

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/localfiletreetable/LocalFileTreeTablePresenter.java

Somehow I didn't catch we were missing a letter

fileSelect

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/DeepStorageBrowserPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/ShutdownServiceImpl.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/Ds3PanelPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/interruptedjobwindow/JobInfoListTreeTableItem.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/interruptedjobwindow/JobInfoPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/newsession/NewSessionPresenter.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/ds3Panel/CreateService.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/ds3Panel/DeleteService.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/ds3Panel/Ds3PanelService.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/BucketUtil.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/CancelJobsWorker.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/StringBuilderUtil.java
dsb-integration/src/test/java/com/spectralogic/dsbrowser/integration/tasks/CreateBucketTaskTest.java
dsb-integration/src/test/java/com/spectralogic/dsbrowser/integration/tasks/Ds3DeleteFilesTaskTest.java

These are a collection of very small fixes that didn't belong anywhere else.

Minor fixes that didn't belong in any other PR

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/ds3treetable/Ds3TreeTablePresenter.java

After mucking with context menus in 5.0.3 I forgot a place .

Fixed issue where search turned of versions

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/Ds3PanelPresenter.java

See BPB-517, there was a case where the label was preserved.

Small fix, clears label after last session is closed

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/localfiletreetable/LocalFileTreeTablePresenter.java
dsb-gui/src/main/resources/lang_en.properties

When creating a folder, the behavior was inconsistent between the left and right pane, now the behavior should be consistent between panes.

Small fix so windows folder creation behave how Cliff expects

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/ds3panel/Ds3PanelPresenter.java

Small change, there was another place we need to have logic to set/clear the breadcrumb label.

Tab switching works consistently now

---

dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/components/interruptedjobwindow/JobInfoListTreeTableItem.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/services/tasks/SearchJobTask.java
dsb-gui/src/main/java/com/spectralogic/dsbrowser/gui/util/StringBuilderUtil.java

Small tweaks to make searching more responsive.

Search in parallel
